version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: p5oTPU+Eo36dAruK7Eo6rs7WABeoqV1cb1kzvzVXcN3gZhcxjNmQTkDT8nM0ziK4
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(assembly_version)
  assembly_file_version: $(assembly_version)
  assembly_informational_version: $(assembly_informational_version)
install:
- ps: >-
    $version = Get-Content ./Stubble.Extensions.JsonNet/version.json -Raw | ConvertFrom-Json;

    $assembly_version = "$($version.major).$($version.minor).$($version.patch).$($env:APPVEYOR_BUILD_NUMBER)";

    $env:assembly_version=$assembly_version;
    $env:assembly_informational_version=$assembly_version;

    Update-AppveyorBuild -Version $assembly_version;

    if($version.packagePostfix) {
        $assembly_informational_version = $assembly_version + "-" + $version.packagePostfix;
        $env:assembly_informational_version=$assembly_informational_version;
    }
before_build:
- nuget restore
build:
  project: Stubble.Extensions.JsonNet.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- ps: >-
    $Package_Locations = ".\packages";
    $OpenCover_Location = Get-ChildItem ($Package_Locations + "\OpenCover*\tools") | Select-Object -First 1 -ExpandProperty FullName;
    $Xunit_Location = Get-ChildItem ($Package_Locations + "\xunit.runner.console*\tools") | Select-Object -First 1 -ExpandProperty FullName;
    $CoverallsNet_Location = Get-ChildItem ($Package_Locations + "\coveralls.net*") | Select-Object -First 1 -ExpandProperty FullName;

    $openCoverExe = "$OpenCover_Location\OpenCover.Console.exe -register:user -target:""$Xunit_Location\xunit.console.exe"" ""-targetargs:"""".\Stubble.Core.Tests\bin\$env:CONFIGURATION\Stubble.Core.Tests.dll"""" -noshadow -appveyor"" -filter:""+[Stubble.*]*"" -skipautoprops -output:coverage.xml";
    $coverallsExe = "$CoverallsNet_Location\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage ""$env:APPVEYOR_REPO_COMMIT_MESSAGE"" --jobId $env:APPVEYOR_JOB_ID"

    iex $openCoverExe;
    iex $coverallsExe;
artifacts:
- path: Stubble\bin\$(Configuration)\Stubble.Extensions.JsonNet.dll
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
